import type {Options} from 'prettier';

export default {
  printWidth: 80,
  tabWidth: 2,
  useTabs: false,
  semi: true,
  singleQuote: true,
  jsxSingleQuote: false,
  trailingComma: 'all',
  bracketSpacing: false,
  bracketSameLine: false,
  rangeStart: 0,
  rangeEnd: Infinity,
  // parser: '',
  // filepath: string,
  requirePragma: false,
  insertPragma: false,
  proseWrap: 'preserve',
  arrowParens: 'always',
  // plugins: [],
  htmlWhitespaceSensitivity: 'css',
  endOfLine: 'lf',
  quoteProps: 'consistent',
  vueIndentScriptAndStyle: false,
  embeddedLanguageFormatting: 'auto',
} as Options;
